runtime: python311

env_variables:
  PYTHONPATH: /app
  E2B_API_KEY: e2b_9b129e91de746c08cd412d15b0f9a3ec2ae014c1
  E2B_TEMPLATE_ID: lnmzb0eecin3qojbvl9j

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto