name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: 'Deploy to Cloud Run'
      run: |
        gcloud run deploy e2b-code-execution-api \
          --source . \
          --platform managed \
          --region asia-northeast3 \
          --allow-unauthenticated \
          --set-env-vars="E2B_API_KEY=${{ secrets.E2B_API_KEY }}" \
          --project=${{ secrets.GCP_PROJECT_ID }}